# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airot < Formula
  desc "Track Claude Code, Cursor and Codex sessions in the AIRot iPhone app"
  homepage "https://github.com/JordaoGustavo/homebrew-airot"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JordaoGustavo/homebrew-airot/releases/download/v0.4.0/airot_0.4.0_darwin_amd64.tar.gz"
      sha256 "c52d392a18ad96d269f172b5ad2204815c9eacd0dba6690b61e58540c7cb7226"

      define_method(:install) do
        bin.install "airot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JordaoGustavo/homebrew-airot/releases/download/v0.4.0/airot_0.4.0_darwin_arm64.tar.gz"
      sha256 "1fe125fab44b7329023d477946df288ed62e3608ace52691569e4c0f3bedf492"

      define_method(:install) do
        bin.install "airot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordaoGustavo/homebrew-airot/releases/download/v0.4.0/airot_0.4.0_linux_amd64.tar.gz"
      sha256 "8c1a4c99170e9ab895eb89ab74a00783084a0f89f9740f4411fa0b7208c2f974"
      define_method(:install) do
        bin.install "airot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordaoGustavo/homebrew-airot/releases/download/v0.4.0/airot_0.4.0_linux_arm64.tar.gz"
      sha256 "88257091827ec65e59305738c20a6ff00d86caabd83208af1b672a9deab5f561"
      define_method(:install) do
        bin.install "airot"
      end
    end
  end

  def caveats
    <<~EOS
      Conecte ao app AIRot:  airot pair
      Depois instale os hooks:  airot hooks install --all
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/airot --version")
  end
end
