# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airot < Formula
  desc "Track Claude Code, Cursor and Codex sessions in the AIRot iPhone app"
  homepage "https://github.com/JordaoGustavo/homebrew-airot"
  version "0.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JordaoGustavo/homebrew-airot/releases/download/v0.5.1/airot_0.5.1_darwin_amd64.tar.gz"
      sha256 "35bf314c3c039bcd58845dddfdc26a286120a33826f0f2c8acec36276bb3a3e8"

      define_method(:install) do
        bin.install "airot"
        libexec.install "AIRot Notifier.app" if OS.mac? && File.exist?("AIRot Notifier.app")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JordaoGustavo/homebrew-airot/releases/download/v0.5.1/airot_0.5.1_darwin_arm64.tar.gz"
      sha256 "34137ac5baafeb3e9aae3cafd73aef3870b518f29286adc84754a65ab38271ff"

      define_method(:install) do
        bin.install "airot"
        libexec.install "AIRot Notifier.app" if OS.mac? && File.exist?("AIRot Notifier.app")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordaoGustavo/homebrew-airot/releases/download/v0.5.1/airot_0.5.1_linux_amd64.tar.gz"
      sha256 "9ed5555eebb6e05ee926767a3a5711f8ee7cf7feb5fefe363feec2b2280ce757"
      define_method(:install) do
        bin.install "airot"
        libexec.install "AIRot Notifier.app" if OS.mac? && File.exist?("AIRot Notifier.app")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordaoGustavo/homebrew-airot/releases/download/v0.5.1/airot_0.5.1_linux_arm64.tar.gz"
      sha256 "5709abf93a58ccc7580ec7b9fb351fa4fcd387e851ee40b1407b1297258acd39"
      define_method(:install) do
        bin.install "airot"
        libexec.install "AIRot Notifier.app" if OS.mac? && File.exist?("AIRot Notifier.app")
      end
    end
  end

  def caveats
    <<~EOS
      Conecte ao app AIRot:  airot pair
      Depois instale os hooks:  airot hooks install --all
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/airot --version")
  end
end
